channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.2
- pip:
  - mlflow==3.2.0
  - astunparse==1.6.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - optree==0.14.0
  - pandas==2.2.3
  - torch==2.8.0
  - torchvision==0.23.0
name: mlflow-env
