paths:
  data_path: data

model_parameters:
  image_size: [128, 128]
  batch_size: 32
  epochs: 10

model_training_parameters:
  model_path: temp_best_model
  hyperparameter_sets:
    - learning_rate: 0.009
      num_filters: 16
      kernel_size: [3, 3]
    - learning_rate: 0.0005
      num_filters: 32
      kernel_size: [3, 3]
    - learning_rate: 0.001
      num_filters: 64
      kernel_size: [5, 5]

mlflow:
  inference_model_name: Production_Reg
  inference_model_alias: prod
  experiment_name: Defect_Detection_CNN
  evaluation_threshold: 0.70
  production_model_name: Production_Reg
  testing_model_name: Testing_Reg

inference_examples:
  defective_image: test/def_front/cast_def_0_1153.jpeg
  ok_image: test/ok_front/cast_ok_0_10.jpeg
