name: Defect Detection Pipeline (Local MLflow)

on:
  push:
    branches:
      - main

jobs:
  defect-detection:
    runs-on: self-hosted  # Your local Mac or custom runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade --force-reinstall mlflow==2.12.1
        pip install -r requirements.txt

    - name: (Optional) Clean old MLflow artifacts (only if fresh run required)
      run: rm -rf mlruns.db mlruns

    - name: Start MLflow Tracking Server
      run: |
        nohup mlflow server \
          --host 0.0.0.0 \
          --port 5000 \
          --backend-store-uri sqlite:///mlruns.db \
          --default-artifact-root ./mlruns > mlflow.log 2>&1 &
        sleep 10  # Give server time to boot

    - name: Preprocess Data
      run: python preprocess/preprocess.py --config preprocess/config.yaml

    - name: Train Model
      run: python training/train.py --config training/config.yaml --mlflow_config mlflow_config.yaml

    - name: Evaluate Model
      run: python evaluation/evaluate.py --config evaluation/config.yaml --mlflow_config mlflow_config.yaml

    - name: Deploy Model (Set 'prod' alias)
      run: |
        echo "If evaluation is successful, the 'prod' alias will be set for the model."
        echo "This is handled within the evaluation/evaluate.py script."

    - name: Run Inference (Example)
      run: |
        DUMMY_IMAGE_PATH="data/test/ok_front/cast_ok_0_10.jpeg"
        if [ -f "$DUMMY_IMAGE_PATH" ]; then
          python inference/infer.py --config inference/config.yaml --mlflow_config mlflow_config.yaml --image_path "$DUMMY_IMAGE_PATH"
        else
          echo "Dummy image not found at $DUMMY_IMAGE_PATH. Skipping inference example."
        fi
