name: MLOps Defect Detection Pipeline

on: [push]


jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'arm64'

    - name: Configure pip cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Set MLflow Tracking URI
      run: echo "MLFLOW_TRACKING_URI=http://localhost:5000/" >> $GITHUB_ENV

    - name: Run Training Script
      run: python train/train.py

    - name: Run Evaluation Script
      run: python evaluation/evaluation.py

    - name: Run Inference Script
      run: python inference/inference.py
